version: 2.1

orbs:
  android: circleci/android@2.0.3
jobs:
  build-and-test:
    executor: 
      name: android/android-machine
      tag: 2023.04.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: Save test results
          command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  android-workflows:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master